=== examar72/XmlBlackBox/template-project/src/test/resources/xsd/xmlblackbox_1_7.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xbb="http://www.xmlblackbox.org/xsd/" elementFormDefault="qualified" targetNamespace="http://www.xmlblackbox.org/xsd/" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    
<xs:complexType name="DB-CONNECTIONS">
	<xs:annotation>
		<xs:documentation>
			Identify a database connection
		</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="CONNECTION" type="xbb:CONNECTION" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="version" type="xbb:connection-version" use="required"/>
</xs:complexType>


<xs:complexType name="CONNECTION">
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="driver" type="xs:string" use="required"/>
	<xs:attribute name="db-url" type="xs:string" use="required"/>
	<xs:attribute name="username" type="xs:string" use="required"/>
	<xs:attribute name="password" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="SELENIUM-SERVER">
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="port" type="xs:string" use="required"/>
	<xs:attribute name="version" type="xbb:selenium-server-version"/>
	<xs:attribute name="operation" type="xbb:selenium-server-operation" use="required"/>
</xs:complexType>

<xs:complexType name="SELENIUM-CLIENT">
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="server-port" type="xs:string" use="required"/>
	<xs:attribute name="server-ip" type="xs:string" use="required"/>
	<xs:attribute name="domain" type="xs:string" use="required"/>
	<xs:attribute name="browser-type" type="xs:string" use="required"/>
	<xs:attribute name="version" type="xbb:selenium-client-version"/>
</xs:complexType>

<xs:simpleType name="setVariableType">
	<xs:restriction base="xs:string">
		<xs:pattern value="XML_TYPE|VALUE_TYPE|DB_TYPE|OBJ_TYPE" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="browserType">
	<xs:restriction base="xs:string">
		<xs:pattern value="FIREFOX|IEXPLORER|CHROME|HTMLUNIT" />
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="SET-VARIABLE">
	<xs:annotation>
		<xs:documentation>
			Identify a step for setting variable
		</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="SET" type="xbb:SET" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="version" type="xbb:setvariable-version" use="required"/>
</xs:complexType>

<xs:complexType name="SET">
	<xs:attribute name="connection" type="xs:string" use="optional"/>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="value" type="xs:string" use="optional"/>
	<xs:attribute name="query" type="xs:string" use="optional"/>
	<xs:attribute name="bean" type="xs:string" use="optional"/>
	<xs:attribute name="filename" type="xs:string" use="optional"/>
	<xs:attribute name="namespace" type="xs:string" use="optional"/>
	<xs:attribute name="xpath" type="xs:string" use="optional"/>
	<xs:attribute name="type" type="xbb:setVariableType" use="required"/>
	<xs:attribute name="repository" type="xs:string" use="optional"/>
</xs:complexType>

<xs:complexType name="WAIT-TASK">
	<xs:annotation>
		<xs:documentation>
			Identify a step for setting variable
		</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="WAIT" type="xbb:WAIT" minOccurs="1"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="connection" type="xs:string" use="required"/>
	<xs:attribute name="version" type="xbb:setvariable-version" use="required"/>
</xs:complexType>

<xs:complexType name="WAIT">
	<xs:attribute name="timeout" type="xs:string" use="required"/>
	<xs:attribute name="query" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="EXECUTE-QUERY">
	<xs:annotation>
		<xs:documentation>
			Identify a step for executing query
	</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="QUERY" type="xbb:QUERY" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="version" type="xbb:executequery-version" use="required"/>
</xs:complexType>

<xs:complexType name="QUERY">
	<xs:attribute name="connection" type="xs:string" use="required"/>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="query" type="xs:string" use="required"/>
	<xs:attribute name="type" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="CHECK-DB">
	<xs:annotation>
		<xs:documentation>
			Identify a step for db check
	</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="dataset" type="xbb:dataset" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="version" type="xbb:checkdb-version" use="required"/>
	<xs:attribute name="connection" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="RUN-PLUGIN">
	<xs:annotation>
		<xs:documentation>
			Identify a step for run a plugin
	</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="PARAMETERS" type="xbb:PARAMETERS" minOccurs="0"/>
	</xs:sequence>
	<xs:attribute name="version" type="xbb:runplugin-version" use="required"/>
	<xs:attribute name="class" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="PARAMETERS">
	<xs:choice>
		<xs:element name="PARAMETER" type="xbb:PARAMETER" minOccurs="1" maxOccurs="unbounded"/>
	</xs:choice>
</xs:complexType>

<xs:complexType name="PARAMETER">
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="value" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="XML-CONTENT">
	<xs:annotation>
		<xs:documentation>
			Identify a step for checking xml file content
	</xs:documentation>
	</xs:annotation>
  	<xs:choice maxOccurs="unbounded">
		<xs:element name="XML-INSERT-ROW" type="xbb:XML-ROW" minOccurs="0"/>
		<xs:element name="XML-CHECK-ROW" type="xbb:XML-ROW" minOccurs="0"/>
	</xs:choice>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="version" type="xbb:xmlcontent-version" use="required"/>
	<xs:attribute name="fileinput" type="xs:string" use="required"/>
	<xs:attribute name="fileoutput" type="xs:string" use="optional"/>
	<xs:attribute name="namespace" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="XML-ROW">
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="xpath" type="xs:string" use="required"/>
	<xs:attribute name="value" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="WEB-SERVICE-CLIENT">
	<xs:annotation>
		<xs:documentation>
			Identify a step for executing a web service call
		</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="FILE-INPUT" type="xs:string" minOccurs="0" maxOccurs="1"/>
		<xs:element name="FILE-OUTPUT" type="xs:string" minOccurs="0" maxOccurs="1"/>
		<xs:element name="URL" type="xs:string" minOccurs="0" maxOccurs="1"/>
		<xs:element name="STUB" type="xs:string" minOccurs="0" maxOccurs="1"/>
		<xs:element name="OPERATION" type="xs:string" minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="optional"/>
	<xs:attribute name="version" type="xbb:webserviceclient-version" use="optional"/>
	<xs:attribute name="input-file" type="xs:string" use="optional"/>
	<xs:attribute name="output-file" type="xs:string" use="optional"/>
	<xs:attribute name="url" type="xs:string" use="optional"/>
	<xs:attribute name="stub" type="xs:string" use="optional"/>
	<xs:attribute name="operation" type="xs:string" use="optional"/>
</xs:complexType>

<xs:complexType name="dataset">
	<xs:annotation>
		<xs:documentation>
			Identify a dataset in the db check
    	</xs:documentation>
	</xs:annotation>
	<xs:choice>
        <xs:element name="table" type="xbb:table" minOccurs="1" maxOccurs="unbounded"/>
	</xs:choice>
</xs:complexType>

<xs:complexType name="table">
	<xs:annotation>
		<xs:documentation>
			Identify a table in the db check
    	</xs:documentation>
	</xs:annotation>
  	<xs:choice maxOccurs="unbounded">
        <xs:element name="column" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="row" type="xbb:table-row" minOccurs="1" maxOccurs="unbounded"/>
	</xs:choice>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="where-condition" type="xs:string" use="required"/>
	<xs:attribute name="is-present" type="xbb:type-is-present" use="optional"/>
</xs:complexType>

<xs:complexType name="table-row">
	<xs:annotation>
		<xs:documentation>
			Identify a table-row in the db check
    	</xs:documentation>
	</xs:annotation>
	<xs:sequence>
        <xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="SELENIUM">
	<xs:annotation>
		<xs:documentation>
			Identify a step for executing a web navigation
		</xs:documentation>
	</xs:annotation>
	<xs:sequence>
        <xs:element name="NAVIGATION-FILE" type="xbb:NAVIGATION-FILE" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="version" type="xbb:selenium-version" use="required"/>
	<xs:attribute name="selenium-client" type="xs:string" use="optional"/>
</xs:complexType>

<xs:complexType name="SELENIUM-WEB-DRIVER-CLIENT">
	<xs:annotation>
		<xs:documentation>
			Identify a step for executing a web navigation with Selenium Web Driver
		</xs:documentation>
	</xs:annotation>
	<xs:sequence>
        <xs:element name="NAVIGATION-FILE" type="xbb:NAVIGATION-FILE" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="browser-session" type="xs:string" use="optional"/>
	<xs:attribute name="browser-type" type="xbb:browserType" use="required"/>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="version" type="xbb:selenium-version" use="required"/>
</xs:complexType>


<xs:complexType name="NAVIGATION-FILE">
	<xs:choice>
        <xs:element name="PARAMETERS" type="xbb:PARAMETERS" minOccurs="0"/>
	</xs:choice>
	<xs:attribute name="class" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="VALIDATE-XML">
	<xs:annotation>
		<xs:documentation>
			Identify a step for validating an xml file
		</xs:documentation>
	</xs:annotation>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="version" type="xbb:validate-version" use="required"/>
	<xs:attribute name="xml" type="xs:string" use="required"/>
	<xs:attribute name="xsd" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="INCLUDE-FILE">
	<xs:annotation>
		<xs:documentation>
			Identify a step for including other xml file
		</xs:documentation>
	</xs:annotation>
	<xs:attribute name="version" type="xbb:includefile-version" use="required"/>
	<xs:attribute name="filename" type="xs:string" use="required"/>
</xs:complexType>

<xs:element name="TEST" type="xbb:TEST"/>
<xs:element name="VALIDATE-XML" type="xbb:VALIDATE-XML"/>
<xs:element name="DB-CONNECTIONS" type="xbb:DB-CONNECTIONS"/>
<xs:element name="SET-VARIABLE" type="xbb:SET-VARIABLE"/>
<xs:element name="EXECUTE-QUERY" type="xbb:EXECUTE-QUERY"/>
<xs:element name="CHECK-DB" type="xbb:CHECK-DB"/>
<xs:element name="RUN-PLUGIN" type="xbb:RUN-PLUGIN"/>
<xs:element name="XML-CONTENT" type="xbb:XML-CONTENT"/>
<xs:element name="WEB-SERVICE-CLIENT" type="xbb:WEB-SERVICE-CLIENT"/>
<xs:element name="SELENIUM" type="xbb:SELENIUM"/>
<xs:element name="SELENIUM-WEB-DRIVER-CLIENT" type="xbb:SELENIUM-WEB-DRIVER-CLIENT"/>
<xs:element name="INCLUDE-FILE" type="xbb:INCLUDE-FILE"/>
<xs:element name="WAIT-TASK" type="xbb:WAIT-TASK"/>
<xs:element name="SELENIUM-SERVER" type="xbb:SELENIUM-SERVER"/>
<xs:element name="SELENIUM-CLIENT" type="xbb:SELENIUM-CLIENT"/>

<xs:complexType name="TEST">
	<xs:annotation>
		<xs:documentation>
			Identify the main tag
		</xs:documentation>
	</xs:annotation>
	<xs:choice maxOccurs="unbounded">
		<xs:element ref="xbb:VALIDATE-XML" />
		<xs:element ref="xbb:DB-CONNECTIONS" />
		<xs:element ref="xbb:SET-VARIABLE" />
		<xs:element ref="xbb:EXECUTE-QUERY" />
		<xs:element ref="xbb:CHECK-DB" />
		<xs:element ref="xbb:RUN-PLUGIN" />
		<xs:element ref="xbb:XML-CONTENT" />
		<xs:element ref="xbb:WEB-SERVICE-CLIENT" />
		<xs:element ref="xbb:SELENIUM" />
		<xs:element ref="xbb:SELENIUM-WEB-DRIVER-CLIENT" />
		<xs:element ref="xbb:INCLUDE-FILE" />
        <xs:element ref="xbb:WAIT-TASK" />
	    <xs:element ref="xbb:SELENIUM-SERVER" />
	    <xs:element ref="xbb:SELENIUM-CLIENT" />
	</xs:choice>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="version" type="xbb:test-version" use="required"/>
</xs:complexType>

<xs:simpleType name="selenium-server-operation">
	<xs:restriction base="xs:string">
		<xs:pattern value="start|stop" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="type-is-present">
	<xs:restriction base="xs:string">
		<xs:pattern value="true|false" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="selenium-server-version">
	<xs:restriction base="xs:string">
		<xs:pattern value="1.1" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="selenium-client-version">
	<xs:restriction base="xs:string">
		<xs:pattern value="1.1" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="connection-version">
	<xs:restriction base="xs:string">
		<xs:pattern value="1.0|1.1" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="setvariable-version">
	<xs:restriction base="xs:string">
		<xs:pattern value="1.0|1.1" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="executequery-version">
	<xs:restriction base="xs:string">
		<xs:pattern value="1.0|1.1" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="runplugin-version">
	<xs:restriction base="xs:string">
		<xs:pattern value="1.0|1.1" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="checkdb-version">
	<xs:restriction base="xs:string">
		<xs:pattern value="1.0|1.1" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="xmlcontent-version">
	<xs:restriction base="xs:string">
		<xs:pattern value="1.0|1.1" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="webserviceclient-version">
	<xs:restriction base="xs:string">
		<xs:pattern value="1.0|1.1|1.2" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="selenium-version">
	<xs:restriction base="xs:string">
		<xs:pattern value="1.0|1.1" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="validate-version">
	<xs:restriction base="xs:string">
		<xs:pattern value="1.0|1.1" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="test-version">
	<xs:restriction base="xs:string">
		<xs:pattern value="1.0|1.1" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="includefile-version">
	<xs:restriction base="xs:string">
		<xs:pattern value="1.0|1.1" />
	</xs:restriction>
</xs:simpleType>

</xs:schema>

=== examar72/XmlBlackBox/template-project/src/test/java/org/xmlblackbox/test/functional/examples/v37/ExampleVersion37_003.xml
<?xml version="1.0" encoding="utf-8" ?>
<TEST version="1.1" 
	name="ExampleVersion37_003"
	xmlns="http://www.xmlblackbox.org/xsd/" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.xmlblackbox.org/xsd/ ../../../../../../../resources/xsd/xmlblackbox_1_7.xsd">


    <!-- Example to do a selenium web driver navigation with HtmlUnitDriver-->
    <SELENIUM-WEB-DRIVER-CLIENT version="1.1" name="Example37 with SELENIUM WEB DRIVER CLASS" browser-type="HTMLUNIT">
            <NAVIGATION-FILE class="org.xmlblackbox.test.functional.examples.v37.selenium.WebApplicationTestWebDriver">
                <PARAMETERS>
                        <PARAMETER name="EXAMPLE_WEB_URL" value="${EXAMPLE_WEB_URL@inputProperties}"/>
                </PARAMETERS>
            </NAVIGATION-FILE>
    </SELENIUM-WEB-DRIVER-CLIENT>

    <SELENIUM-WEB-DRIVER-CLIENT version="1.1" name="Example37 with SELENIUM WEB DRIVER CLASS Next Page" browser-type="HTMLUNIT">
            <NAVIGATION-FILE class="org.xmlblackbox.test.functional.examples.v37.selenium.WebApplicationTestWebDriverNextPage"/>
    </SELENIUM-WEB-DRIVER-CLIENT>


    <!-- Example to do a selenium web driver navigation with PhantomjsDriver-->
    <SELENIUM-WEB-DRIVER-CLIENT browser-session="Phantom" version="1.1" name="Example37 with SELENIUM WEB DRIVER CLASS" browser-type="PHANTOMJS">
            <NAVIGATION-FILE class="org.xmlblackbox.test.functional.examples.v37.selenium.WebApplicationTestWebDriver">
                <PARAMETERS>
                        <PARAMETER name="EXAMPLE_WEB_URL" value="${EXAMPLE_WEB_URL@inputProperties}"/>
                </PARAMETERS>
            </NAVIGATION-FILE>
    </SELENIUM-WEB-DRIVER-CLIENT>

    <SELENIUM-WEB-DRIVER-CLIENT browser-session="Phantom" version="1.1" name="Example37 with SELENIUM WEB DRIVER CLASS Next Page" browser-type="PHANTOMJS">
            <NAVIGATION-FILE class="org.xmlblackbox.test.functional.examples.v37.selenium.WebApplicationTestWebDriverNextPage"/>
    </SELENIUM-WEB-DRIVER-CLIENT>

</TEST>
